version: '2'
services:

  php:
    image: jguillermo/php-apache:7.1
    volumes:
      - ./:/var/www/html
    ports:
      - 8081:80

#  postgres:
#    image: jguillermo/postgres:9.6
#    environment:
#      POSTGRES_PASSWORD: toor
#      POSTGRES_USER : root
#      POSTGRES_DB: dbproject
#    ports:
#      - 5439:5432
#    volumes:
#     - .volumes/postgresql:/var/lib/postgresql/data

  mysql:
    image: jguillermo/mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: toord
      MYSQL_USER : root
      MYSQL_DATABASE: dbproject
    ports:
      - 3359:3306
    volumes:
      - .volumes/mysql:/var/lib/mysql
