version: '2'
services:

  php:
    image: jguillermo/php-apache:7.1
    build:
      context: ./docker/php-apache/

  cli:
      image: jguillermo/php-cli:7.1
      build:
        context: ./docker/php-cli/

  postgres:
    image: jguillermo/postgres:9.6
    build:
      context: ./docker/postgres/

  mysql:
      image: jguillermo/mysql:5.6
      build:
        context: ./docker/mysql/